services:
  - type: web
    name: boligregnskap-demo
    env: docker
    plan: free
    envVars:
      - key: SPRING_H2_CONSOLE_ENABLED
        value: "false"
      - key: SPRING_PROFILES_ACTIVE
        value: "demo"
